sonar.projectKey=ramissac_backend_russbell
sonar.projectName=RamisSac Backend
sonar.projectVersion=1.0

# 1. Rutas del código fuente y de los tests
# SonarQube leerá tu carpeta 'app' y buscará las pruebas en 'tests'
sonar.sources=app
sonar.tests=test

# 2. Configuración del Lenguaje
sonar.language=py
sonar.python.version=3.10

# 3. Exclusiones (archivos que no quieres que SonarQube analice)
# Excluimos entornos virtuales y archivos de configuración
sonar.exclusions=**/venv/**, **/migrations/**, **/__init__.py

# 4. Integración de reportes de calidad generados por Pytest (Sprint 1)
sonar.python.coverage.reportPaths=coverage.xml